language: go

sudo: false

osx_image: xcode8.2

go:
  - 1.4
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover


after_success:
    - artifacts upload $HOME/gopath/bin/moire

notifications:
    email:
        - samsabra@gmail.com